package com.ytt.mapper;

import com.ytt.model.RUser;
import com.ytt.model.RUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbg.generated
     */
    int insert(RUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbg.generated
     */
    int insertSelective(RUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbg.generated
     */
    List<RUser> selectByExample(RUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RUser record, @Param("example") RUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RUser record, @Param("example") RUserExample example);
}